feat: 使用 XML 定义卡片消息
gehongyan/Kook.Net pull request #9
Opened 2024-03-17 07:08 UTC by LiamSho

impl #8 

可能需要的改动：

- 文档
- 多出一个 NuGet Package
- 把 `spec/card-message.xsd` 放到 `https://kooknet.dev/card-message.xsd` ?

2024-03-17 10:00 UTC, gehongyan reviewed
1. 或许 PR 中的 README.md 可以移动到文档中。
2. 当前请将 `Kook.Net.CardMarkup.csproj` 中的 `IsPackable` 设置为 `false`，待下一版本我再改成 `true` 同步发包，也需要包含在 `Kook.Net` 包中。
3. 可以在 `docfx.json` 中添加引用
```diff
Index: docs/docfx.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/docs/docfx.json b/docs/docfx.json
--- a/docs/docfx.json	(revision f787c312ac6b46aab7640bcd5ad3aed9c29a85a6)
+++ b/docs/docfx.json	(date 1710668558369)
@@ -67,6 +67,12 @@
                     "**/obj/**",
                     "**.meta"
                 ]
+            },
+            {
+                "files": [
+                    "card-message.xsd"
+                ],
+                "src": "../spec"
             }
         ],
         "dest": "_site",
```

---

另外，可否添加一些单元测试呢？

2024-03-17 10:00 UTC, gehongyan commented on spec/README.md
计划移动至文档中，新开一个卡片消息的目录，将当前页作为独立页面包含进去。

> https://github.com/gehongyan/Kook.Net/tree/master/docs/guides

2024-03-17 10:00 UTC, gehongyan commented on spec/card-message.xsd
> +            <xs:attribute name="cols" type="xs:int" use="required" />
XSD 的语法支持这里定义最小值和最大值分别为 1 和 3 嘛

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/CardMarkupSerializer.cs
> +    /// <returns></returns>
添加对返回值的说明

```suggestion
    /// <returns>
    ///     A task that represents the asynchronous deserialization operation.
    ///     The task result contains a list of <see cref="ICard"/> objects deserialized from the XML file.
    /// </returns>
```

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/CardMarkupSerializer.cs
> +    /// <returns></returns>
添加对返回值的说明

```suggestion
    /// <returns>
    ///     A task that represents the asynchronous deserialization operation.
    ///     The task result contains a list of <see cref="ICard"/> objects deserialized from the XML text.
    /// </returns>
```

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/CardMarkupSerializer.cs
> +    /// <returns></returns>
添加对返回值的说明

```suggestion
    /// <returns>
    ///     A task that represents the asynchronous deserialization operation.
    ///     The task result contains a list of <see cref="ICard"/> objects deserialized from the XML stream.
    /// </returns>
```

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/Extensions/CardBuilderExtensions.cs
> +namespace Kook.CardMarkup.Extensions;
降低命名空间深度，卡片标记语言扩展相关代码可都使用 `Kook.CardMarkup` 命名空间。

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/CardMarkupSerializer.cs
可否添加 Deserialize 同步方法及 TryDeserialize 方法呢

2024-03-17 10:00 UTC, gehongyan commented on src/Kook.Net.CardMarkup/Kook.Net.CardMarkup.csproj
> +    <IsPackable>true</IsPackable>
待下一版本我再改成 true 同步发包

```suggestion
    <IsPackable>false</IsPackable>
```

2024-03-17 10:00 UTC, gehongyan commented on spec/examples/vote.xml
计划移动至 samples

> https://github.com/gehongyan/Kook.Net/tree/master/samples

2024-03-17 10:00 UTC, gehongyan commented on spec/examples/weibo.xml
计划移动至 samples

> https://github.com/gehongyan/Kook.Net/tree/master/samples

2024-03-17 10:00 UTC, gehongyan commented on spec/card-message.xsd
> +    <!-- ================= Root ================== -->
这会导致 IDE 展示 card-message 标记的描述为该内容

![image](https://github.com/gehongyan/Kook.Net/assets/21241496/22ba05a5-b142-4b47-aa03-d5bd7f605853)

2024-03-18 02:50 UTC, LiamSho commented on spec/card-message.xsd
> +            <xs:attribute name="cols" type="xs:int" use="required" />
使用自定义类型解决

```xml
    <xs:simpleType name="type-column-count">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
            <xs:maxInclusive value="3" />
        </xs:restriction>
    </xs:simpleType>
```

2024-03-18 02:50 UTC, LiamSho commented on spec/card-message.xsd
> +    <!-- ================= Root ================== -->
没有在 Rider 和 VSCode 里发现这样的情况。现在打算用 XSD 的 annotation 打上注释，应该就不会这样了。

2024-03-18 07:57 UTC, gehongyan commented on spec/card-message.xsd
> +    <!-- ================= Root ================== -->
好哦

2024-03-19 02:16 UTC, gehongyan requested changes

2024-03-19 02:16 UTC, gehongyan commented on spec/card-message.xsd
> +    </xs:simpleType>
文件标题或许应该是纯文本格式

2024-03-19 02:16 UTC, gehongyan commented on samples/Kook.Net.Samples.CardMarkup/Cards/big-card.xml
> +      <countdown end="1710758046409" start="1710754446409" mode="second" />
这里的 end 时间戳早于当前时间时，会导致卡片校验失败，如果可以的话，请设置一个合理较大的时间戳

2024-03-19 02:16 UTC, gehongyan commented on samples/Kook.Net.Samples.CardMarkup/Cards/big-card.xml
> +      <invite code="CJlEJE"/>
该邀请码会过期。

```suggestion
      <invite code="EvxnOb"/>
```

2024-03-19 05:28 UTC, gehongyan requested changes

2024-03-19 05:28 UTC, gehongyan commented on samples/Kook.Net.Samples.CardMarkup/Cards/big-card.xml
> +          <plain>内容模块，无 Accessary</plain>
```suggestion
          <plain>内容模块，无 Accessory</plain>
```

2024-03-19 05:28 UTC, gehongyan commented on docs/guides/card_markup/card.md
> +KooK 消息编辑器中的投票消息模版。
```suggestion
KOOK 消息编辑器中的投票消息模版。
```

2024-03-19 05:28 UTC, gehongyan commented on docs/guides/card_markup/elements.md
> +[KooK 开发者文档 - 卡片消息 - 元素](https://developer.kookapp.cn/doc/cardmessage#%E5%85%83%E7%B4%A0)
```suggestion
[KOOK 开发者文档 - 卡片消息 - 元素](https://developer.kookapp.cn/doc/cardmessage#%E5%85%83%E7%B4%A0)
```

2024-03-19 05:28 UTC, gehongyan commented on docs/guides/card_markup/modules.md
> +[KooK 开发者文档 - 卡片消息 - 模块](https://developer.kookapp.cn/doc/cardmessage#%E6%A8%A1%E5%9D%97)
```suggestion
[KOOK 开发者文档 - 卡片消息 - 模块](https://developer.kookapp.cn/doc/cardmessage#%E6%A8%A1%E5%9D%97)
```

2024-03-19 05:28 UTC, gehongyan commented on docs/guides/card_markup/structures.md
> +[KooK 开发者文档 - 卡片消息 - 结构体](https://developer.kookapp.cn/doc/cardmessage#%E7%BB%93%E6%9E%84%E4%BD%93)
```suggestion
[KOOK 开发者文档 - 卡片消息 - 结构体](https://developer.kookapp.cn/doc/cardmessage#%E7%BB%93%E6%9E%84%E4%BD%93)
```

2024-03-19 05:33 UTC, gehongyan approved these changes

2024-03-19 05:37 UTC, merged

2024-03-19 05:52 UTC, gehongyan commented
感谢！辛苦了！